version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run: git clone https://github.com/StackStorm/ansible && cd ansible
      - run: git checkout slxos_modules
      - run: pip install -r requirements.txt
      - run: pip install ansible-lint
      - run: . ./hacking/env-setup
      - run: ansible-lint */*/*.yaml
