version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run: git clone https://github.com/StackStorm/ansible && cd ansible && git checkout slxos_modules
      - run: pip install -r ansible/requirements.txt
      - run: pip install ansible-lint
      - run: . ./ansible/hacking/env-setup && ansible-lint -v slxos/playbooks/*.yaml
