version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/StackStorm/ansible
            cd ansible
            git checkout slxos_modules
            pip install -r requirements.txt
            . ./hacking/env-setup
            pip install ansible-lint
            cd ../slxos/playbooks
            ansible-lint -v *.yaml
